### ISSUE TITLE
Is this project abondoned for still being maintanied?

### ISSUE THREAD

**Issue by Blason** [armbues/ioc_parser#42]
HI,

I am getting below error while installing ioc-parser on my Ubuntu 18.04

`Collecting pdfminer>=20140328 (from -r ../requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/cb/4a/625b0772fb422a055b30f72a92231b57bf36ac4747acb56240bb0a29edae/pdfminer-20191016.tar.gz
Requirement already satisfied: PyPDF2>=1.26.0 in /usr/local/lib/python2.7/dist-packages (from -r ../requirements.txt (line 3))
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r ../requirements.txt (line 4))
Requirement already satisfied: soupsieve<2.0 in /usr/local/lib/python2.7/dist-packages (from beautifulsoup4>=4.4.1->-r ../requirements.txt (line 1))
Requirement already satisfied: pycryptodome in /usr/local/lib/python2.7/dist-packages (from pdfminer>=20140328->-r ../requirements.txt (line 2))
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.10.0->-r ../requirements.txt (line 4))
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.10.0->-r ../requirements.txt (line 4))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.10.0->-r ../requirements.txt (line 4))
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.10.0->-r ../requirements.txt (line 4))
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve<2.0->beautifulsoup4>=4.4.1->-r ../requirements.txt (line 1))
Building wheels for collected packages: pdfminer
  Running setup.py bdist_wheel for pdfminer ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jfQUWz/pdfminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpUKD_v1pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/cmapdb.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/utils.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/glyphlist.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/pdfdevice.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/rijndael.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/encodingdb.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/fontmetrics.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/pdfinterp.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/pdftypes.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/ccitt.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/latin_enc.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/image.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/ascii85.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/pdfdocument.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/pdfcolor.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/runlength.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/psparser.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/converter.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/pdffont.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/arcfour.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/pdfparser.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/layout.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/pdfpage.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/__init__.py -> build/lib.linux-x86_64-2.7/pdfminer
  copying pdfminer/lzw.py -> build/lib.linux-x86_64-2.7/pdfminer
  running build_scripts
  creating build/scripts-2.7
  copying and adjusting tools/pdf2txt.py -> build/scripts-2.7
  copying and adjusting tools/dumppdf.py -> build/scripts-2.7
  changing mode of build/scripts-2.7/pdf2txt.py from 644 to 755
  changing mode of build/scripts-2.7/dumppdf.py from 644 to 755
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-jfQUWz/pdfminer/setup.py", line 71, in <module>
      'Topic :: Text Processing',
    File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 162, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 240, in run
      self.run_command('install')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-jfQUWz/pdfminer/setup.py", line 11, in run
      from pdfminer.cmapdb import convert_cmap
    File "pdfminer/cmapdb.py", line 22, in <module>
      from .psparser import PSStackParser
    File "pdfminer/psparser.py", line 4, in <module>
      from .utils import choplist
    File "pdfminer/utils.py", line 219, in <module>
      0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x00fd, 0x00fe, 0x00ff,
    File "pdfminer/utils.py", line 187, in <genexpr>
      PDFDocEncoding = ''.join(chr(x) for x in (
  ValueError: chr() arg not in range(256)

  ----------------------------------------
  Failed building wheel for pdfminer
  Running setup.py clean for pdfminer
Failed to build pdfminer
Installing collected packages: pdfminer
  Running setup.py install for pdfminer ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jfQUWz/pdfminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9vyjnJ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jfQUWz/pdfminer/setup.py", line 71, in <module>
        'Topic :: Text Processing',
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-jfQUWz/pdfminer/setup.py", line 11, in run
        from pdfminer.cmapdb import convert_cmap
      File "pdfminer/cmapdb.py", line 22, in <module>
        from .psparser import PSStackParser
      File "pdfminer/psparser.py", line 4, in <module>
        from .utils import choplist
      File "pdfminer/utils.py", line 219, in <module>
        0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x00fd, 0x00fe, 0x00ff,
      File "pdfminer/utils.py", line 187, in <genexpr>
        PDFDocEncoding = ''.join(chr(x) for x in (
    ValueError: chr() arg not in range(256)

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jfQUWz/pdfminer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9vyjnJ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-jfQUWz/pdfminer/
`

**Comment by lc4nt** [comment]
I created an installable version which is compatible with python 3. https://github.com/lc4nt/ioc-parser. I'm willing to push a PR here if the project is still maintained.

**Comment by armbues** [comment]
I haven't been actively working on any improvements for a while since most reports have switched over to web (instead of PDF) and/or made their IOCs more accessible.
